Make pylint calm down.
pythonista-cloud/cloud pull request #3
Opened 2016-09-30 03:03 UTC by teamnoire

Just some minor changes to make pylint shutup (and increase readability a little bit).

2016-09-30 11:01 UTC, controversial reviewed
Looks overall good, I should've caught the `zip` thing.

2016-09-30 11:01 UTC, controversial commented on _cloud/__init__.py
> +    metadata = None
Confused about where this variable is later referenced

2016-09-30 11:01 UTC, controversial commented on _cloud/__init__.py
> +    metadata = None
There is a metadata variable, but why does it need to be defined here?

2016-09-30 22:54 UTC, teamnoire commented on _cloud/__init__.py
> +    metadata = None
There are lines which define `self._zip` and `self.metadata` out of the `__init__` function (which triggers pylint for some reason).

2016-09-30 22:57 UTC, controversial commented on _cloud/__init__.py
> +    metadata = None
I don't think pylint is something we're developing against. I'm using pep8 and pyflakes. Let me take a look when I get to a laptop in a few hours, though.

2016-09-30 23:00 UTC, teamnoire commented on _cloud/__init__.py
> +    metadata = None
I just want to make sure I can focus at the real warnings, instead of having the editor over saturated with those silly ones.

2016-10-01 00:55 UTC, controversial requested changes
Can you take al the changes out besides the doctoring fix and changing `zip` to `_zip`? Also, I think something like `zipfile` would make more sense than `_zip` since it's not a private attribute. I'll merge after this. I'd just prefer not to have the top-level definitions of `_zip` and `metadata` as `None`. Thanks!

2016-10-01 00:56 UTC, controversial commented
Pretend I said "docstring" and it wan't autocorrected there ;)

2016-10-02 19:47 UTC, merged